### ISSUE TITLE
Feature Request: Falling Speed

### ISSUE THREAD

**Issue by qbicc-4** [PhylacteryLost/Desktop-Mascot#1]
Hey I really love your software and how easy it is to customize =)

I would highly appreciate a feature that allows the user to modify the falling speed of the mascot. (And maybe others would too)

Kind  Regards
Felix

**Comment by MasterOfCreatures** [comment]
Hi Felix,

i did some hacking in my fork. I just used a factor to manipulate the gravitational Speed.
If you go below 0 the mascot starts floating upwards.
Just take a look here:
https://github.com/MasterOfCreatures/Desktop-Mascot/commit/823989ba6fb67119c6c4070b0bb43e704bc355a1#diff-d02285234b0d2e15bfb730bb719a02405d4bab08dc836e4f1287c2f4771eb099

or basically just do this(0.2 is the factor):
`gameObject.Position.Y += (int)Math.Floor(moveDistPerSecond*0.2);`

better you don't use my fork it is so chopped up that it only works with 2 screens in the right order.

greetings 
MOC

**Comment by qbicc-4** [comment]
Hi MOC,

Thanks a lot, with your help I was able to do it =)
